version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm ci
            - run: npm test
      - codecov/upload:
          file: tests/coverage/*.json
workflows:
    build-and-test:
      jobs:
        - build-and-test
